config/routes.rb
FbIrcLogviewer::Application.routes.draw do
  resources :irc_channels, :only => [:index, :show] do
    resources :log_files, :only => [:show]
    get 'search' => 'search#search'
  end
  get 'sitemap' => 'irc_channels#sitemap'
  root :to => 'irc_channels#index'
end

app/models/irc_channel.rb
class IrcChannel < ActiveRecord::Base
  attr_accessible :name
  has_many :log_files

  def self.name_from_file(file_name)
    if file_name =~ /\#([\w_]+)_\d{8}/
      return "#"+$1
    end
    return nil
  end

end

app/models/log_entry.rb
class LogEntry < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  attr_accessible :what, :when, :who, :log_file_id
  belongs_to :log_file

  mapping do
    indexes :id,   :index    => :not_analyzed
    indexes :log_file_id, :index => :not_analyzed
    indexes :who,  :analyzer => 'keyword'
    indexes :what, :analyzer => 'snowball'
    indexes :when, :type     => 'date'
  end

  # [18:56:33] <taxilian_away> jakepetroules: yes, that is correct
  def self.new_from_line(log_file, line)
    return unless log_file && line
    line.chomp!
    begin
      regexp = /\[([\d\:]+)\] <(.*?)> /
      if line =~ regexp
        line_time = $1
        line_who  = $2
        line_what = line.gsub(regexp, '')

        file_date = log_file.file_date.strftime('%Y%m%d')
        log_when = Time.strptime("#{file_date} #{line_time}", "%Y%m%d %H:%M:%S")

        log_file.log_entries.where(:when => log_when, :who => line_who, :what => line_what).first_or_create!
      end
    rescue Exception => e
      puts "#{log_file.file_name}: unable to load: #{line}\nmessage:#{e.to_s}"
    end
  end


  # takes a time-sorted array of LogEntry records
  # returns an array of arrays of LogEntry records, clustered around who and when
  def self.cluster(entries)
    clustered = []

    prev_who = prev_when = ''
    current_cluster = []
    entries.each do |e|
      cluster = (prev_who == e.who && e.when - prev_when < 500 )

      unless cluster
        clustered.push current_cluster if current_cluster.size > 0
        current_cluster = []
      end

      current_cluster.push e

      prev_who = e.who
      prev_when = e.when
    end

    return clustered
  end
end

app/models/log_file.rb
class LogFile < ActiveRecord::Base
  attr_accessible :file_date, :file_name
  belongs_to :irc_channel
  has_many :log_entries

  def self.new_from_file_name(irc_channel, file_name)
    if file_name =~ /(\d{8})/
      return LogFile.where(:irc_channel_id => irc_channel.id, :file_name => File.basename(file_name))
        .first_or_create!(:file_date => Date.strptime($1, '%Y%m%d'))
    end
    return nil
  end

  def self.load(file_name)
    if channel_name = IrcChannel.name_from_file(file_name)
      irc_channel = IrcChannel.where(:name => channel_name).first_or_create!
      puts "#{file_name}: loading channel #{irc_channel.name}"
      if log_file = LogFile.new_from_file_name(irc_channel, file_name)
        File.open(file_name, 'r') do |f|
          while line = f.gets
            LogEntry.new_from_line(log_file, line)
          end
        end
      else
        puts "#{file_name}: could not create a new LogFile entry?"
      end

    else
      puts "#{file_name}: could not extract channel name from file name"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/irc_channels_controller.rb
class IrcChannelsController < ApplicationController

  respond_to :xml
  def sitemap
    @irc_channels = IrcChannel.all
    respond_to do |format|
      format.xml { render 'sitemap' }
      format.any { render :text => "Only XML is currently supported."}
    end
  end

  def index
    @irc_channels = IrcChannel.all
  end

  def show
    @irc_channel = IrcChannel.find(params[:id])
    raise ActionController::RoutingError.new('Not Found') unless @irc_channel
    @log_files = @irc_channel.log_files.order('file_date desc')
  end
end

app/controllers/log_files_controller.rb
class LogFilesController < ApplicationController
  def show
    @log_file = LogFile.find(params[:id])
    raise ActionController::RoutingError.new('Not Found') unless @log_file
    @clustered_log_entries = LogEntry.cluster(@log_file.log_entries.order('id asc'))
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @irc_channel = IrcChannel.find(params[:irc_channel_id])
    raise ActionController::RoutingError.new('IrcChannel required for search') unless @irc_channel

    page = params[:page] || 1
    q = params[:query]
    @results = LogEntry.search(page: page, per_page: 30, :load => true)do
      query { string q } if q.present?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/irc_channels/index.html.erb
<h1>IRC Channels</h1>

<ol>
<% @irc_channels.each do |irc_channel| %>
  <li><%= link_to(irc_channel.name, irc_channel_path(irc_channel)) %></li>
<% end %>
</ol>

app/views/irc_channels/show.html.erb
<h2><%= link_to("IRC Log Viewer", root_path) %> &raquo; <%= @irc_channel.name %></h2>
<%= render :partial => 'search/form', :locals => { :irc_channel => @irc_channel } %>
<% @log_files.each do |log_file| %>
  <span style="padding: 10px 8px 8px 10px;"><%= link_to(log_file.file_date, irc_channel_log_file_path(@irc_channel, log_file)) %></span>
<% end %>

app/views/irc_channels/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
  <loc><%= "#{request.protocol}#{request.host_with_port}" %></loc>
  <changefreq>daily</changefreq>
</url>

<% @irc_channels.each do |irc_channel| %>
  <url>
    <loc><%= "#{request.protocol}#{request.host_with_port}#{irc_channel_path(irc_channel)}" %></loc>
    <changefreq>daily</changefreq>
  </url>
  <% irc_channel.log_files.order("id desc").each_with_index do |log_file, i| %>
    <url>
      <loc><%= "#{request.protocol}#{request.host_with_port}#{irc_channel_log_file_path(irc_channel, log_file)}" %></loc>
      <changefreq><%= i == 0 ? 'hourly' : 'daily' %></changefreq>
    </url>
  <% end %>
<% end %>
</urlset>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FbIrcLogviewer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
  <div class="span1"></div>
  <div class="span12">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/log_files/show.html.erb
<h2><%= link_to("IRC Log Viewer", root_path) %> &raquo; <%= link_to @log_file.irc_channel.name, irc_channel_path(@log_file.irc_channel) %> &raquo; <%= @log_file.file_date %></h2>
<table class="table table-striped">
<thead>
    <tr class="info">
        <th>IRC Nick</th>
        <th>Time (GMT-7)</th>
        <th>Message</th>
    </tr>
</thead>
<tbody>
  <% @clustered_log_entries.each do |clustered_log_entry| %>
    <% log_entry = clustered_log_entry.shift %>
    <tr>
      <td class="log_entry_who"><%= log_entry.who %></td>
      <td class="log_entry_when"><%= log_entry.when.getlocal.strftime("%H:%m") %></td>
      <td><a class="named_a" name="log_entry_<%= log_entry.id %>"><%= log_entry.what %></a>
        <% clustered_log_entry.each do |log_entry| %>
          <hr class="log_cluster_separator"/><a class="named_a" name="log_entry_<%= log_entry.id %>"><%= log_entry.what %></a>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/search/_form.html.erb
<%= form_tag irc_channel_search_path(irc_channel), :method => 'get' do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag :Search, :name => nil %>
  </p>
<% end %>

app/views/search/search.html.erb
<h2><%= link_to("IRC Log Viewer", root_path) %> &raquo; <%= @irc_channel.name %></h2>
<%= render :partial => 'search/form', :locals => { :irc_channel => @irc_channel } %>

<h3><%= @results.total %> results</h3>

<% if @results.size > 0 %>
<table class="table table-striped">
  <thead>
    <tr class="info">
      <th>IRC Nick</th>
      <th>Date</th>
      <th>Time (GMT-7)</th>
      <th>Message</th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do |log_entry| %>
      <tr>
        <td class="log_entry_who"><%= link_to log_entry.who, irc_channel_log_file_path(@irc_channel, log_entry.log_file, :anchor => "log_entry_#{log_entry.id}") %></td>
        <td class="log_entry_when"><%= log_entry.when.getlocal.strftime("%Y-%m-%d") %></td>
        <td class="log_entry_when"><%= log_entry.when.getlocal.strftime("%H:%m") %></td>
        <td><%= log_entry.what %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @results %>
<% end %>